FROM devopsedu/webapp
MAINTAINER "chinmaya"
RUN apt-get update
RUN apt-get install -y git
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get update
RUN apt-get install -y php
RUN mkdir /var/www/html/project
RUN git clone https://github.com/cpuroh/Project1.git /var/www/html/project
EXPOSE 80
CMD apachectl -D FOREGROUND